version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - "Type: Maintenance"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "actions/*"
      labeling:
        patterns:
          - "EndBug/*"
    labels:
      - "Type: Maintenance"
